/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BankAccountDTO { 
    id?: string;
    appUserId: string;
    name: string;
    accountType?: string;
    currentBalance: number;
    createdAt?: string;
    plaidAccountId?: string;
    plaidItemId?: string;
    accountMask?: string;
    manual?: boolean;
    institutionName?: string;
    plaidLinkedAt?: string;
}

