/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EnvelopeDTO { 
    id?: string;
    appUserId: string;
    name: string;
    allocatedBalance: number;
    createdAt?: string;
}

