/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlaidAccountLink } from './plaidAccountLink';


export interface ExchangeTokenRequest { 
    publicToken: string;
    institutionId?: string;
    institutionName?: string;
    accountLinks: Array<PlaidAccountLink>;
}

