/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankAccountDTO } from './bankAccountDTO';


export interface PlaidItemDTO { 
    id?: string;
    institutionId?: string;
    institutionName?: string;
    status?: string;
    lastSyncedAt?: string;
    createdAt?: string;
    accounts?: Array<BankAccountDTO>;
}

