/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransactionDTO { 
    id?: string;
    appUserId: string;
    bankAccountId: string;
    envelopeId?: string;
    amount: number;
    description?: string;
    transactionDate: string;
    createdAt?: string;
}

